#!/usr/bin/env bash
# Script that displays listening TCP/UDP ports with PID/Program

echo "Active Internet connections (only servers)"
sudo netstat -lntup

echo "Active UNIX domain sockets (only servers)"
sudo netstat -lnp --unix
