#!/usr/bin/env bash
# Script to change localhost IP to

HOSTS_FILE="/etc/hosts"
BACKUP_FILE="/etc/hosts.bak.$(date +%F_%T)"

sudo cp $HOSTS_FILE $BACKUP_FILE
echo "Backup saved at: $BACKUP_FILE"

if grep -q "^127\.0\.0\.1\s\+localhost" $HOSTS_FILE; then
    sudo sed -i 's/^127\.0\.0\.1\s\+localhost/127.0.0.2 localhost/' $HOSTS_FILE
else
    echo "127.0.0.2 localhost" | sudo tee -a $HOSTS_FILE
fi

if grep -q "facebook.com" $HOSTS_FILE; then
    sudo sed -i 's/^.*facebook\.com.*/8.8.8.8 facebook.com/' $HOSTS_FILE
else
    echo "8.8.8.8 facebook.com" | sudo tee -a $HOSTS_FILE
fi
